name: Automatic MLOps Pipeline

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas numpy scikit-learn xgboost mlflow evidently kaggle

      - name: Download Kaggle dataset
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          kaggle datasets download -d sriharshaeedala/financial-fraud-detection-dataset -p .

      - name: Preprocess dataset
        run: |
          python preprocess_data.py

      - name: Run MLOps pipeline
        run: |
          python run_mlops_pipeline.py